def gtf(xyz:list[float],lmn:list[int],alp:float)->float:...

def cgf(xyz:list[float],lmn:list[int],alps:list[float],coes:list[float])->float:...

def ato_wfn(xyz:list[float],xyzs:list[list[float]],lmns:list[list[int]],coes:list[list[float]],alps:list[list[float]])->float:...

def mol_rho(xyz:list[float],xyzs:list[list[float]],lmns:list[list[int]],coes:list[list[float]],alps:list[list[float]],mat_c:list[list[float]])->float:...